# List of PR labels for readline

tags:
- tag.go
- internal/tag/*
commands:
- command.go
- gen/flags/command*
flags:
- flag.go
- camelcase*
- gen/flags/flags*
positionals:
- internal/positional/*
- gen/flags/positional*
completions:
- gen/completions/*
options:
- options.go
- internal/scan/options.go
scan:
- parser.go
- errors.go
- parser_test.go
- internal/scan/*
validation:
- validator/*
- internal/validation/*
types:
- internal/convert/*
- cmd/genvalues/*
- values*
- converters*
